In [2]:
import pandas as pd
import re
import numpy as np
from deep_translator import GoogleTranslator


URL="http://dart.fss.or.kr/report/viewer.do?rcpNo=20200331002575&dcmNo=7216196&eleId=13&offset=687340&length=115750&dtd=dart3.xsd"
# new_url=URL.replace("20200330004817",new_rcpnumber).replace("7208566",new_dcmnumber)
detector = GoogleTranslator(source='auto', target='en')
table=pd.read_html(URL)
data=table[1]
template=pd.read_excel("template2.xlsx")
reference=pd.read_excel("Korea Dictionary.xlsx")
colu=list(data.columns)
# template["LocalDescriptions"]=data[colu[0]]
template["LocalDescriptions"]=pd.concat([data[colu[0]]]*3,ignore_index=True)
template['EngDescriptions'] = template['LocalDescriptions'].apply(detector.translate)
# dict1=pd.Series(reference.EngDescriptions.values,index=reference.LocalDescriptions).to_dict()
# template['EngDescriptions'] = template['LocalDescriptions'].apply(lambda x:(dict1[x]))
# template["LineItemValue"]=pd.concat([data[colu[1]],data[colu[2]],data[colu[3]]],ignore_index=True)
# template=template.merge(reference, on='LocalDescriptions', how='left')
# b['EngDescriptions'] = b['LocalDescriptions'].apply(detector.translate, src='ko', dest='en').apply(getattr, args=('text',))
template["FinStmtType"]="BAL"
template["Currency"]="KRW"
template["AsReportedDescription"]=template["EngDescriptions"]
template["EditedDescription"]=template["EngDescriptions"]
template["EditedDescription"]=template["EngDescriptions"]
template["TableName"]=table[0][0][0]

denomination=str(table[0].iloc[-1:,:])
if "(단위 : 원)" in denomination:
    template["ReportingMultiplier"]="1"
elif "(단위 : 천원)" in denomination:
    template["ReportingMultiplier"]="1000"
elif "(단위 : 백만원)" in denomination:
    template["ReportingMultiplier"]="10000"

# elif table[0].iloc[-1:,:]=="(단위 : 천원)":
#     template["ReportingMultiplier"]=1000
# elif table[0].iloc[-1:,:]=="(단위 : 백만원)":
#     template["ReportingMultiplier"]=10000

row=data.shape[0]
column=data.shape[1]
a = np.random.choice(np.arange(0, 1000), replace=False, size=(row, column))
data2=pd.DataFrame(a,columns=list(table[1].columns))
number=[]
row_index=[]
col_index=[]
for column in data2.columns:
    string=re.compile("\D\s\d\d\s\D")
    result=string.match(column)
    if result!=None:
        for z in data[column]:
            if z==np.nan:
                number.append("NULL")
            else:
                number.append(z)

        for i in data2[column]:
            a=np.where(data2 == i)[0]
            for i in a:
                row_index.append(i)

        for i in data2[column]:
            b=np.where(data2 == i)[1]
            for j in b:
                col_index.append(j)

col_index_series=pd.Series(col_index)
row_index_series=pd.Series(row_index)
number_series=pd.Series(number)

template["LineItemValue"]=number_series
template["ReportedValue"]=number_series
template["ValueY"]=row_index_series
template["ValueX"]=col_index_series
template["RowOrder"]=template["ValueY"]
template["MultiDimensionalTableFlag"]=0
template["FYEndDate"]=np.nan
template.fillna("NULL",inplace=True)
template.to_excel("ouput_template2-new2.xlsx")

print("success")

success

,LocalDescriptions,EngDescriptions_x,ID,BatchID,PageNumber,TableIndex,ValueY,ValueX,TableId,RowID,...,MapType,IsExcluded,CTPBatchfileID,UserID,NormRowid,NormRowOrder,NormParentRowID,SystemStartDateTime,SystemEndDateTime,EngDescriptions_y
0,과 목,Section1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,유동자산,유동자산계,NULL,NULL,NULL,NULL,1.0,1.0,NULL,NULL,...,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,유동자산계
2,유동자산,유동자산계,NULL,NULL,NULL,NULL,2.0,1.0,NULL,NULL,...,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,Current Assets
3,유동자산,유동자산계,NULL,NULL,NULL,NULL,44.0,2.0,NULL,NULL,...,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,유동자산계
4,유동자산,유동자산계,NULL,NULL,NULL,NULL,45.0,2.0,NULL,NULL,...,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,Current Assets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8737,투자주식T,Invmt Stock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8738,현금T,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8739,현금및현금성자산T,Cash & Cash Equivalents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8740,확정급여부채T,Non-Current Defined Benefit Liabilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8741,확정급여채무T,Non-Current Defined Benefit Liabilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN